name: CI

on:
  push:
    branches:
      - main
  
jobs:
  build:
    name: Buld
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: |
         cd app
         npm install
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: |
         cd infra-azure
         npm install
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: dev
          work-dir: infra-azure
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          AUTH_GITHUB_USERNAME: ${{ secrets.AUTH_GITHUB_USERNAME }}
          AUTH_GITHUB_TOKEN: ${{ secrets.AUTH_GITHUB_TOKEN }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          APPROVAL_API_KEY: ${{ secrets.ACTIONS_APPROVAL_API_KEY }}
